name: Agrovision
description: "تطبيق إدارة المزرعة الذكي"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  # Networking
  http: ^1.2.2
  # Image picking & camera
  image_picker: ^1.1.2
  # Local storage for settings
  shared_preferences: ^2.3.3
  # State management
  provider: ^6.1.2
  flutter_secure_storage: ^10.0.0
  tflite_flutter: ^0.12.1
  image: ^4.8.0
  csv: ^6.0.0
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_app_2cp.jpg
    - assets/models/bean_dynamic.tflite
    - assets/models/Apple.tflite
    - assets/models/Cherry_(including_sour).tflite
    - assets/models/Corn_(maize).tflite
    - assets/models/Grape.tflite
    - assets/models/lentil_chikpea.tflite
    - assets/models/Peach.tflite
    - assets/models/Pepper,_bell.tflite
    - assets/models/Potato.tflite
    - assets/models/Strawberry.tflite
    - assets/models/Tomato.tflite

